### ISSUE TITLE
6.x Sniff Error

### ISSUE THREAD

**Issue by alexandre433** [TrinityCore/WowPacketParser#263] opened 2016-09-05 00:56 UTC
Hello,
Today I used the sniff on my legion server, then i dragged the .pkt file to the .exe and then it gave me this error.
https://gyazo.com/3775c031532c83a1cacf074680897caf

Help?

**Comment by tkrokli** [comment] 2016-09-05 01:00
Looks like something in HotfixData needs to be set to `int64` instead of `int32` .

**Comment by alexandre433** [comment] 2016-09-05 01:05
So is the problem local? or not?

**Comment by tkrokli** [comment] 2016-09-05 01:50
That needs to be confirmed by a real developer, but I imagine it is in the WPP source.

**Comment by skmagiik** [comment] 2016-09-05 02:40
Can you upload the pkt that you were trying to parse?

**Comment by alexandre433** [comment] 2016-09-05 10:03
There you go
https://mega.nz/#!9VZRiIwC
It was from the starter area of the pandarens

**Comment by jcmillions** [comment] 2016-09-05 18:27
+1 on this issue, but this is a great project! :)

**Comment by alexandre433** [comment] 2016-09-06 09:59
up

**Comment by Aokromes** [comment] 2016-09-06 10:20
it will be fixed when it's fixed.

**Comment by alexandre433** [comment] 2016-09-08 23:58
UPDATE

I found something, that it is related to this issue https://github.com/TrinityCore/TrinityCore/issues/17903

When I use the "attach_sniffer_64.cmd" and start walking around, and it crashes the .pkt files maybe gets corrupted or something and then there's no way you can use it to add it to your server or to make it an .sql.

**Comment by jcmillions** [comment] 2016-09-11 07:21
I hate to be a bother about this, but has anyone looked into this?

**Comment by Aokromes** [comment] 2016-09-11 08:26
https://github.com/TrinityCore/WowPacketParser/issues/263#issuecomment-244909806

**Comment by alexandre433** [comment] 2016-09-11 11:14
So basicly, no ^^

**Comment by tkrokli** [comment] 2016-09-11 21:07
Well, it depends. It depends on those who maintain WPP and what they think of your issue.

**Comment by alexandre433** [comment] 2016-09-12 10:11
Judging from this comment https://github.com/TrinityCore/WowPacketParser/issues/263#issuecomment-244909806 I don't think they care much about my issue, basicly I just need to wait, he didn't even give me a solution or something saying that they cannot solve atm.

**Comment by alexandre433** [comment] 2016-09-18 09:49
**UPDATE**

In each sniff I "added" to the WowPacketParser.exe it whould stop loading in "Hotfixdata" and "ObjectNames" so I disabled them and no more errors.

Which means they are bugged, atleast that's what I think.

**Closed** 2016-10-09 00:58 UTC

**Comment by DDuarte** [comment] 2016-10-09 01:00
This was probably fixed in 181117d15305537dc5a81f737981c8e2b2be054c
