### ISSUE TITLE
System.OverflowException?

### ISSUE THREAD

**Issue by ic3cr34m** [TrinityCore/WowPacketParser#245] opened 2016-05-03 14:57 UTC
I know I've been posting a lot of issues, but I finally downloaded the uncompiled version of WPP and while parsing I got this error:

```
[1/1 21463_2016-05-02_21-53-38_1FFD524F.pkt]: Parsing 16.5MB of packets. Detecte
d version V6_2_4_21463
Processing... 100% complete
[1/1 21463_2016-05-02_21-53-38_1FFD524F.pkt]: Saved file to 'C:\Program Files (x
86)\World of Warcraft\21463_2016-05-02_21-53-38_1FFD524F_parsed.txt'
[1/1 21463_2016-05-02_21-53-38_1FFD524F.pkt]: Parsed 4472 (4.536%) packets succe
ssfully, 76776 (77.882%) with errors, skipped 4 (0.004%) and without structure 1
7328 (17.578%)  (total: 98580) in 00:00:16.046
1/71 - Write HotfixData
2/71 - Write AreaPOI
3/71 - Write AreaPOIState
4/71 - Write BattlePetSpecies
5/71 - Write BroadcastText
6/71 - Write ChrUpgradeTier
7/71 - Write ChrUpgradeBucket
8/71 - Write ChrUpgradeBucketSpell
9/71 - Write Creature
10/71 - Write CreatureDifficulty
11/71 - Write CurvePoint
12/71 - Write HolidayData
13/71 - Write Item
14/71 - Write ItemAppearance
15/71 - Write ItemBonus
16/71 - Write ItemBonusTreeNode
17/71 - Write ItemCurrencyCost
18/71 - Write ItemEffect
19/71 - Write ItemExtendedCost
20/71 - Write ItemModifiedAppearance
21/71 - Write ItemSparse
22/71 - Write GameObjects
23/71 - Write KeyChain
24/71 - Write Location
25/71 - Write Mount
26/71 - Write OverrideSpellData
27/71 - Write PhaseXPhaseGroup
28/71 - Write SceneScript
29/71 - Write SpellAuraRestrictions
30/71 - Write SpellCastingRequirements
31/71 - Write SpellClassOptions
32/71 - Write SpellEffectGroupSize
33/71 - Write SpellLearnSpell
34/71 - Write SpellMisc
35/71 - Write SpellPower
36/71 - Write SpellReagents
37/71 - Write SpellTotems
38/71 - Write Toy
39/71 - Write BroadcastTextLocale
40/71 - Write LocalesQuest
41/71 - Write LocalesQuestObjectives
42/71 - Write StartInformation
43/71 - Write ObjectNames
44/71 - Write SniffData
45/71 - Write WeatherUpdates
46/71 - Write QuestOfferReward

Unhandled Exception: System.OverflowException: Value was either too large or too
 small for an Int32.
   at System.Convert.ToInt32(UInt32 value)
   at WowPacketParser.SQL.SQLUtil.<>c__DisplayClass14_0`1.<Compare>b__0(T t) in
C:\Users\Administrator\Desktop\WowPacketParser-master\WowPacketParser\SQL\SQLUti
l.cs:line 175
   at WowPacketParser.SQL.SQLUtil.Compare[T](DataBag`1 storeList, RowList`1 dbLi
st, Func`2 commentSetter) in C:\Users\Administrator\Desktop\WowPacketParser-mast
er\WowPacketParser\SQL\SQLUtil.cs:line 261
   at WowPacketParser.SQL.SQLUtil.Compare[T](DataBag`1 storeList, RowList`1 dbLi
st, StoreNameType storeType) in C:\Users\Administrator\Desktop\WowPacketParser-m
aster\WowPacketParser\SQL\SQLUtil.cs:line 175
   at WowPacketParser.SQL.Builders.QuestMisc.QuestOfferReward() in C:\Users\Admi
nistrator\Desktop\WowPacketParser-master\WowPacketParser\SQL\Builders\QuestMisc.
cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at WowPacketParser.SQL.Builder.DumpSQL(String prefix, String fileName, String
 header) in C:\Users\Administrator\Desktop\WowPacketParser-master\WowPacketParse
r\SQL\Builder.cs:line 83
   at WowPacketParser.Program.Main(String[] args) in C:\Users\Administrator\Desk
top\WowPacketParser-master\WowPacketParser\Program.cs:line 68
```

I have been trying to figure this out since last night. It happens when I TRY to parse as a .sql file with all the tabels enabled.
##

**Comment by ic3cr34m** [comment] 2016-05-03 15:01
Edit: Apparently @Aokromes posted a fixed version, but will it work for this case?
I'm just trying it  now.

**Comment by ic3cr34m** [comment] 2016-05-03 15:26
Fixed but for some reason the file it created has some data that's "UNKNOWN".
Any ideas?

**Comment by ic3cr34m** [comment] 2016-05-03 15:30
[database.txt](https://github.com/TrinityCore/WowPacketParser/files/247207/database.txt)

Take a look.

**Comment by Carbenium** [comment] 2016-05-03 17:35
Regarding the "UNKNOWN" fields refer to https://github.com/TrinityCore/TrinityCore/issues/16227#issuecomment-172261358.

If you think the issue is fixed, please close it. Thanks.

**Comment by ic3cr34m** [comment] 2016-05-03 17:38
@Carbenium 
So I think I understand. I have to simply fill it manually?

**Comment by ic3cr34m** [comment] 2016-05-03 18:03
I tried putting one of the queries, and it gave me this:

SQL Error (1136): Column count doesn't match value count at row 1

**Comment by ic3cr34m** [comment] 2016-05-04 18:05
Still having the System.OverflowException error.

**Comment by ChipLeo** [comment] 2016-07-21 06:46
Error in SQLUtil.cs: 
        public static string Compare<T>(DataBag<T> storeList, RowList<T> dbList, StoreNameType storeType)
            where T : IDataModel, new()
        {
            return Compare(storeList, dbList, t => StoreGetters.GetName(storeType, Convert.ToInt32(GetFirstPrimaryKey<T>().GetValue(t)), false));
        }
  - Convert.ToInt32 have argument > int32, how to fix it?

**Comment by jackpoz** [comment] 2017-03-14 15:18
got a sniff that can be used to reproduce the bug ?

**Comment by funjoker** [comment] 2020-10-12 09:17
No more responds from creator and no other responds.

Open a new issue if still needed (with more information)

**Closed by funjoker** 2020-10-12 09:17 UTC
Labels: bug
